import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Tesseract from 'tesseract.js';
import { useState } from "react";
import { useForm } from 'react-hook-form';

export default function Home() {
  //image
  const [preview, setPreview] = useState("");
  const [dataConvert, setdataConvert] = useState("Input Gambar Terlebih Dahulu");

  const loadImage = (e) => {
    const image = e.target.files[0];
    setPreview(URL.createObjectURL(image));

  };

  const convertText = () => {
    if (preview) {
      Tesseract.recognize(
        preview,
        'eng',
        { logger: m => console.log(m) }
      ).then(({ data: { text } }) => {
        setdataConvert(text)
      })
    }

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>OCR</title>
        <meta name="description" content="Generated by Rizky Efrian" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form className=' max-w-2xl'>
          <h1 className=' text-center text-2xl'><b>OCR</b></h1><hr/>
          <div className="field mt-1">
            <div className="control">
              <div className="file">
                <label className="file-label">
                  <input
                    type="file"
                    className="file-input"
                    onChange={loadImage}
                  />
                </label>
              </div>
            </div>
          </div>
          {preview ? (
            <figure className="image is-128x128">
              <Image src={preview} alt='Preview Image' width="500" height="300" />
            </figure>
          ) : (
            ""
          )}

          <div className="form-group">
            <div onClick={() => convertText()} className=" mr-2 bg-blue-500 p-2 mt-5 rounded-lg text-white text-center">
              Save
            </div>
          </div>
          {dataConvert}
        </form>
      </main>
    </div>
  )
}
